### ISSUE TITLE
Cannot parse saved model

### ISSUE THREAD

**Issue by JunxiFeng** [daklab/tiger#4]
Hello,

I am trying to run tiger.py using my machine, but it keeps saying that 

OSError: Cannot parse file b'model/saved_model.pb': Error parsing message.

And I am not sure how to solve the problem. Thanks!

**Comment by astirn** [comment]
Sorry for the delay, for some reason I have not been getting notification of open issues since I transferred the project to my lab's github organization. Let me make some updates and then I will respond in the next day or so.

**Comment by JunxiFeng** [comment]
Thank you so much Andrew!!!!

**Comment by astirn** [comment]
Hey Junxi. Do you have [Git LFS](https://git-lfs.com/) installed? Hugging face encourages storing model weights as LFS objects. You will need git LFS for the pull to work. That said this repository is tied to an older version of the website. I should have this corrected by week's end.

**Comment by JunxiFeng** [comment]
Hi Andrew, thank you so much for your help!

I have now installed git lfs and tried running the code again, and this time there's no error, but the output becomes 

Batch 1 of 200
no saved model!

Thanks!

**Comment by astirn** [comment]
You have a lot of transcripts! Can you try pulling everything from scratch?

**Comment by JunxiFeng** [comment]
Hi Andrew, do you mean deleting everything and then git clone again? I actually tried loading the model from python shell and it works using 

`tiger = tf.keras.models.load_model('/home/juf215/tiger/hugging_face/model')
`
but if I run this in command line `python3 hugging_face/tiger.py --fasta_path ../data/test/`  it would say 

Batch 1 of 200
no saved model!

Thank you!

**Comment by JunxiFeng** [comment]
Hi Andrew, now I can find and parse the model, and I switched to use --simple_test

But now it gives this error:

WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
Finding top guides for each transcript
2023-09-06 12:57:51.637317: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:428] Loaded cuDNN version 8700
Killed

And I am not sure why that is.

Thank you!!

**Comment by JunxiFeng** [comment]
Hi Andrew, I can now run the simple test and generate ouput successfully, but when I run it on my sample data, it says 

  File "/home/juf215/crispr_model/lib/python3.10/site-packages/tensorflow/python/ops/ragged/ragged_concat_ops.py", line 142, in _ragged_stack_concat_helper
    raise ValueError('rt_inputs may not be empty.')
ValueError: rt_inputs may not be empty.

Am I missing something here? 

Thank you!

**Comment by JunxiFeng** [comment]
Hi Andrew, thank you so much for your help!! The code is running as expected now! Thanks again for your time and assistance!!!

**Comment by JunxiFeng** [comment]
Hi Andrew, thank you so much for your help!! The code is running as expected now! Thanks again for your time and assistance!!!
