### ISSUE TITLE
Issue running tiger.py script

### ISSUE THREAD

**Issue by swttalyan** [daklab/tiger#7]
I am trying to run tiger pipeline on CPU with 24GB of memory with same configuration as listed in paper.
Unfortunately script is running for some hours and then failing with the below error, I do not know how to fix it. Some insights would be really appreciated. 
NOTE: This error is persistent was also in the previous version and also in new version on git repo. 
Command used : `python tiger.py --mode top_guides --fasta_path data/ --check_off_targets`

Error Message:
`Scanning for off-targets: 100.00%
Batch 197 of 4738
Evaluating on-target guides for each transcript: 94.00%Traceback (most recent call last):
  File "tiger/hugging_face/tiger.py", line 403, in <module>
    df_on_target, df_titration, df_off_target = tiger_exhibit(
                                                ^^^^^^^^^^^^^^
  File "tiger/hugging_face/tiger.py", line 328, in tiger_exhibit
    on_target_predictions = get_on_target_predictions(transcripts, tiger, status_update_fn)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tiger/hugging_face/tiger.py", line 178, in get_on_target_predictions
    target_seq, guide_seq, model_inputs = process_data(row[SEQ_COL])
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tiger/hugging_face/tiger.py", line 120, in process_data
    tf.reshape(one_hot_encode_sequence(target_seq, add_context_padding=False), [len(target_seq), -1]),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tiger/hugging_face/tiger.py", line 84, in one_hot_encode_sequence
    sequence = tf.ragged.stack([tf.constant(list(seq)) for seq in sequence], axis=0)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".conda/envs/tiger/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File ".conda/envs/tiger/lib/python3.11/site-packages/tensorflow/python/ops/ragged/ragged_concat_ops.py", line 143, in _ragged_stack_concat_helper
    raise ValueError('rt_inputs may not be empty.')
ValueError: rt_inputs may not be empty.
`

Please let me know if you need more details to reproduce this error. I am happy to help. My data is just one fasta file with transcript sequences.

**Comment by JunxiFeng** [comment]
Hi,

I think I ran into the same error before. What are the lengths of your transcript sequences? I think if they're shorter than 26 there will be a problem

`# model hyper-parameters
GUIDE_LEN = 23
CONTEXT_5P = 3
CONTEXT_3P = 0
TARGET_LEN = CONTEXT_5P + GUIDE_LEN + CONTEXT_3P
UNIT_INTERVAL_MAP = 'sigmoid'`

and 

`def process_data(transcript_seq: str):

    # convert to upper case
    transcript_seq = transcript_seq.upper()

    # get all target sites
    target_seq = [transcript_seq[i: i + TARGET_LEN] for i in range(len(transcript_seq) - TARGET_LEN + 1)]
`

Based on these two parts I believe the transcript length must be at least 26 otherwise there will be a problem? But I could be wrong...

**Comment by astirn** [comment]
Thanks Junxi. That is a great point! Running tiger.py does NOT ensure inputs are valid like app.py. @swttalyan can you please make sure all transcripts are at least 26bp in length? I should probably move those checks over....

**Comment by swttalyan** [comment]
Many thanks for your input, is there a time out or something because my script was running for 2 to 3 days, I do not fine any error in my out file but cscript was terminated without running through the all input sequences and I experiences this two times.

**Comment by astirn** [comment]
Sounds like your system is running out of resources. There is no time limit. Once again, please try smaller jobs (e.g. split your FASTA file up).
