### ISSUE TITLE
Issue Can't access tiger.py

### ISSUE THREAD

**Issue by Chloe-AS** [daklab/tiger#8]
Dear Astirn, I encountered the following issues when designing Cas13 gRNA.  First, unable to download tiger.py . got this error message : "fatal: unable to access 'https://huggingface.co/spaces/Knowles-Lab/tiger/': Failed to connect to huggingface.co port 443 after 75465 ms: Operation timed out".  Second, the hungface file is emty.  Could you help out? THX!

**Comment by astirn** [comment]
Can you please confirm:

1. You have git LFS installed
2. You followed the README instructions exactly

I would try again, not sure what's up with huggingface.co
