### ISSUE TITLE
Running TIGER with updated Gencode annotations. Issues with old and new gene names

### ISSUE THREAD

**Issue by tranStephen** [daklab/tiger#9]
Is it possible to run off-target predictions using updated (V44) GENCODE annotations in either the online version TIGER or the local version? I ask because I am stumbling upon gene name conflicts when trying to differentiate off-targets from on-targets. For example GATA2-AS1 in Gencode v44 is named as RP11-475N22.4 in Gencode V19.

**Comment by astirn** [comment]
Hey Tran, Do you want to try and test this for me? I think the following two steps should do the trick:

1. Replace gencode.v19.pc_transcripts.fa.gz and gencode.v19.lncRNA_transcripts.fa.gz in hugging_face/transcripts with the v44 variants.
2. Change line 30 of hugging_face/tiger.py to `REFERENCE_TRANSCRIPTS = ('gencode.v44.pc_transcripts.fa.gz', 'gencode.v44.lncRNA_transcripts.fa.gz')` to reflect the new version number.

Please let me know.

**Comment by tranStephen** [comment]
Thanks for the fast reply!
I'll try this out.

**Comment by tranStephen** [comment]
This worked. Thank you!
